services:
  babybuddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: babybuddy
    volumes:
      - babybuddy_config:/config
    ports:
      - "8015:8000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DJANGO_SETTINGS_MODULE=babybuddy.settings.base
      - SECRET_KEY=CEKt0ZjvHVzlJ5ad14OCmDlS7Aixgplz4_fUiDxrafBAmjbCjdkGiEJi5-QTnWibayk
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO:https
      - CSRF_TRUSTED_ORIGINS=https://baby.meinhomeserver.xyz
      - ALLOWED_HOSTS=baby.meinhomeserver.xyz,localhost
      # Optional:
      # - OLLAMA_ENABLED=1
      # - OLLAMA_URL=http://ollama:11434
      # - OLLAMA_MODEL=llama3.1:8b-instruct

volumes:
  babybuddy_config:
