# Generated by Django 5.0.14 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_recalculate_durations"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="usual_bedtime",
            field=models.TimeField(
                blank=True,
                help_text="Typical bedtime used for sleep recommendations.",
                null=True,
                verbose_name="Usual bedtime",
            ),
        ),
    ]
