# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_child_usual_bedtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="pumping",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right")],
                max_length=32,
                null=True,
                verbose_name="Side",
            ),
        ),
    ]
