# Generated by Django 4.2.29 on 2026-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_pumping_side"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
        migrations.AddField(
            model_name="sleep",
            name="breaks",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Sleep breaks"
            ),
        ),
    ]
