# Generated by Django 4.2.29 on 2026-03-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_bmi_options_alter_headcircumference_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleep",
            name="net_duration",
            field=models.DurationField(
                blank=True, editable=False, null=True, verbose_name="Net duration"
            ),
        ),
    ]
