# Generated by Django 5.1.15 on 2026-03-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_sleep_net_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepTimer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Start time")),
                (
                    "paused_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paused at"
                    ),
                ),
                ("breaks", models.JSONField(default=list, verbose_name="Breaks")),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_timer",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sleep timer",
                "verbose_name_plural": "Sleep timers",
            },
        ),
    ]
