# Generated by Django 5.1.6 on 2026-03-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_sleep_timer_model"),
        ("examinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="examination_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="examinations.examinationprogram",
                verbose_name="Examination program",
            ),
        ),
    ]
