# Generated by Django 5.0 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0035_alter_settings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_show_diaper_section",
            field=models.BooleanField(default=True, editable=True, verbose_name="Show diaper changes section"),
        ),
        migrations.AddField(
            model_name="settings",
            name="dashboard_show_feeding_section",
            field=models.BooleanField(default=True, editable=True, verbose_name="Show feedings section"),
        ),
        migrations.AddField(
            model_name="settings",
            name="dashboard_show_pumping_section",
            field=models.BooleanField(default=True, editable=True, verbose_name="Show pumpings section"),
        ),
        migrations.AddField(
            model_name="settings",
            name="dashboard_show_sleep_section",
            field=models.BooleanField(default=True, editable=True, verbose_name="Show sleep section"),
        ),
        migrations.AddField(
            model_name="settings",
            name="dashboard_show_tummytime_section",
            field=models.BooleanField(default=True, editable=True, verbose_name="Show tummy time section"),
        ),
    ]
