# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0038_cleanup_dashboard_visible_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_hidden_sections",
            field=models.JSONField(blank=True, default=list, verbose_name="Hidden dashboard sections"),
        ),
        migrations.AddField(
            model_name="settings",
            name="dashboard_section_order",
            field=models.JSONField(blank=True, default=list, verbose_name="Dashboard section order"),
        ),
    ]
