# Generated by Django 4.2.29 on 2026-03-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0040_alter_settings_language_alter_settings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="last_used_defaults",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Last used quick-entry defaults"
            ),
        ),
    ]
