# Generated by Django 4.2.29 on 2026-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0041_settings_last_used_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="llm_api_key",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="AI API key"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="llm_base_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="For Ollama: http://localhost:11434",
                max_length=500,
                verbose_name="AI base URL",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="llm_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. llama3, gpt-4o, claude-sonnet-4-6",
                max_length=100,
                verbose_name="AI model",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="llm_provider",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("ollama", "Ollama (local)"),
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                ],
                default="none",
                max_length=20,
                verbose_name="AI provider",
            ),
        ),
    ]
