# Generated by Django 5.1.6 on 2026-03-28 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0041_sleep_timer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, verbose_name='Country code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Examination Program',
                'verbose_name_plural': 'Examination Programs',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('age_min_days', models.IntegerField(verbose_name='Minimum age (days)')),
                ('age_max_days', models.IntegerField(verbose_name='Maximum age (days)')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_types', to='examinations.examinationprogram')),
            ],
            options={
                'verbose_name': 'Examination Type',
                'verbose_name_plural': 'Examination Types',
                'ordering': ['order'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExaminationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('text', models.TextField(verbose_name='Question text')),
                ('doctor_only', models.BooleanField(default=False, verbose_name='Doctor only')),
                ('answer_type', models.CharField(choices=[('boolean', 'Yes / No'), ('text', 'Text'), ('number', 'Number'), ('choice', 'Choice')], default='boolean', max_length=20, verbose_name='Answer type')),
                ('choices', models.JSONField(blank=True, null=True, verbose_name='Choices')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('examination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examinations.examinationtype')),
            ],
            options={
                'verbose_name': 'Examination Question',
                'verbose_name_plural': 'Examination Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of examination')),
                ('answers', models.JSONField(default=dict, verbose_name='Answers')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_records', to='core.child')),
                ('examination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='examinations.examinationtype')),
            ],
            options={
                'verbose_name': 'Examination Record',
                'verbose_name_plural': 'Examination Records',
                'ordering': ['examination_type__order'],
                'unique_together': {('child', 'examination_type')},
            },
        ),
    ]
